# Generated by Django 3.1.3 on 2020-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('regionId', models.AutoField(primary_key=True, serialize=False)),
                ('regionName', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
            ],
        ),
    ]
