# Generated by Django 3.1.3 on 2020-11-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201126_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='size',
            new_name='itemsize',
        ),
    ]
