# Generated by Django 3.1.3 on 2020-11-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201126_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sku',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
